name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn

      - run: |
          yarn install --frozen-lockfile
          yarn test
