on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  add-labels-based-on-whats-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            shared: &shared
              - tokens/**
            add:
              - added: '**'
            update:
              - modified: '**'
            remove:
              - deleted: '**'

      - name: assign Add Token label
        if: steps.filter.outputs.add == 'true'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "add token"

      - name: assign Update Token label
        if: steps.filter.outputs.update == 'true' && steps.filter.outputs.add != 'true'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "update token"

      - name: assign Remove Token label
        if: steps.filter.outputs.remove == 'true'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "remove token"

  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn

      - run: |
          yarn install --frozen-lockfile
          yarn test
